"use client";
import { useMemo, useState } from 'react';
import { Check, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import { Sheet, SheetContent, SheetDescription, SheetTitle } from '@/components/ui/sheet';
import { CATALOG } from './catalog';
import { GROUPS, normalize } from './model';
import { Choose, Credits, ExerciseArt, Heading } from './ui';
import type { Exercise } from './types';
export function ExerciseDetails({exercise,onClose}:{exercise:Exercise|null;onClose:()=>void}){return <Sheet open={!!exercise} onOpenChange={open=>{if(!open)onClose();}}><SheetContent side="bottom" className="mobile-sheet exercise-sheet">{exercise&&<><SheetTitle>{exercise.name}</SheetTitle><SheetDescription>{exercise.equipment} · {exercise.group}</SheetDescription><ExerciseArt exercise={exercise} large/><div className="anatomy-legend"><span className="legend-swatch"/>Área principal em destaque</div><div className="exercise-facts"><div><span>Grupo principal</span><strong>{exercise.group}</strong></div><div><span>Equipamento</span><strong>{exercise.equipment}</strong></div>{exercise.secondary.length>0&&<div><span>Também participa</span><strong>{exercise.secondary.join(', ')}</strong></div>}</div><p className="help-text">Ilustração de referência do movimento. O mapa mostra grupos musculares e não diferencia todas as porções de cada músculo.</p><button className="secondary-btn" onClick={onClose}>Voltar à biblioteca</button></>}</SheetContent></Sheet>;}
export function ExerciseLibrary({selection,existing=[],onToggle,compact=false}:{selection?:string[];existing?:string[];onToggle?:(id:string)=>void;compact?:boolean}){
 const [query,setQuery]=useState('');const [group,setGroup]=useState('all');const [detail,setDetail]=useState<Exercise|null>(null);
 const results=useMemo(()=>CATALOG.filter(e=>(group==='all'||e.group===group)&&normalize(`${e.name} ${e.equipment} ${e.group}`).includes(normalize(query))),[group,query]);
 return <div className={compact?'library-compact':'screen'}>{!compact&&<Heading eyebrow="Conheça cada movimento" title="Biblioteca" description={`${CATALOG.length} exercícios · ${GROUPS.length} grupos musculares`}/>}<div className="library-controls"><label className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque exercício ou equipamento" aria-label="Buscar exercícios"/>{query&&<button type="button" aria-label="Limpar busca" onClick={()=>setQuery('')}><X/></button>}</label><div className="group-filter"><SlidersHorizontal size={17}/><Choose value={group} onChange={setGroup} label="Filtrar por grupo muscular" options={[{value:'all',label:'Todos os grupos'},...GROUPS.map(g=>({value:g,label:g}))]}/></div></div><div className="library-count"><span>{results.length} {results.length===1?'exercício':'exercícios'}</span>{(group!=='all'||query)&&<button className="text-link" onClick={()=>{setGroup('all');setQuery('');}}>Limpar filtros</button>}</div><div className="exercise-grid">{results.map(e=>{const selected=selection?.includes(e.id);const used=existing.includes(e.id);return <article className={`exercise-tile ${selected?'selected':''}`} key={e.id}><button type="button" className="exercise-tile-info" aria-label={`Ver ${e.name}`} onClick={()=>setDetail(e)}><ExerciseArt exercise={e}/><div className="exercise-tile-copy"><span className="muscle-label">{e.group}</span><h3>{e.name}</h3><p>{e.equipment}</p></div></button>{onToggle&&<button type="button" className={`exercise-pick ${selected||used?'picked':''}`} disabled={used} aria-label={`${selected?'Remover seleção de':used?'Já adicionado:':'Selecionar'} ${e.name}`} aria-pressed={selected||used} onClick={()=>onToggle(e.id)}>{selected||used?<Check/>:<Plus/>}</button>}</article>;})}</div>{results.length===0&&<div className="empty-card"><Search/><h3>Nenhum exercício encontrado</h3><p>Tente outro nome ou remova o filtro de grupo.</p></div>}{!compact&&<Credits/>}<ExerciseDetails exercise={detail} onClose={()=>setDetail(null)}/></div>;
}
export function LibraryPicker({open,existing,onClose,onAdd}:{open:boolean;existing:string[];onClose:()=>void;onAdd:(ids:string[])=>void}){
 const [selected,setSelected]=useState<string[]>([]);
 return <Sheet open={open} onOpenChange={v=>{if(!v){setSelected([]);onClose();}}}><SheetContent side="bottom" className="mobile-sheet library-picker"><div className="picker-heading"><SheetTitle>Adicionar exercícios</SheetTitle><SheetDescription>Escolha os movimentos para a sua ficha.</SheetDescription></div><div className="picker-body"><ExerciseLibrary compact existing={existing} selection={selected} onToggle={id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}/></div><div className="picker-footer"><button className="primary-btn" disabled={!selected.length} onClick={()=>{onAdd(selected);setSelected([]);onClose();}}><Plus/>Adicionar {selected.length||''} {selected.length===1?'exercício':'exercícios'}</button></div></SheetContent></Sheet>;
}
