"use client";
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Building2, ChevronRight, Dumbbell, GraduationCap, Search, Shield, User, Users } from 'lucide-react';
import { Avatar, Brand, Choose, Empty, Heading, Section, StudentRow } from './ui';
import { ROLE_LABELS, hasChanges, normalize, statistics, studentHistory, studentPlans } from './model';
import type { Actor, DemoData, Student } from './types';
export function RoleSelector({data,onChoose,onBack}:{data:DemoData;onChoose:(actor:Actor)=>void;onBack?:()=>void}){
 const [autonomous,setAutonomous]=useState(data.actor?.role==='autonomous'?data.actor.id:'rafael');
 const [accompanied,setAccompanied]=useState(data.actor?.role==='accompanied'?data.actor.id:'caue');
 const [teacher,setTeacher]=useState(data.actor?.role==='teacher'?data.actor.id:'bruno');
 const options=[
  {role:'autonomous' as const,id:autonomous,icon:Dumbbell,title:'Aluno autônomo',description:'Monte sua ficha e registre seu treino.',select:<Choose label="Aluno autônomo de exemplo" value={autonomous} onChange={setAutonomous} options={data.students.filter(s=>s.mode==='autonomous').map(s=>({value:s.id,label:s.name}))}/>},
  {role:'accompanied' as const,id:accompanied,icon:User,title:'Aluno acompanhado',description:'Receba a ficha publicada pelo professor.',select:<Choose label="Aluno acompanhado de exemplo" value={accompanied} onChange={setAccompanied} options={data.students.filter(s=>s.mode==='accompanied').map(s=>({value:s.id,label:s.name}))}/>},
  {role:'teacher' as const,id:teacher,icon:GraduationCap,title:'Professor',description:'Escolha o aluno, monte e publique fichas.',select:<Choose label="Professor de exemplo" value={teacher} onChange={setTeacher} options={data.teachers.map(t=>({value:t.id,label:t.name}))}/>},
  {role:'admin' as const,id:'academy',icon:Building2,title:'Admin da academia',description:'Consulte alunos, equipe e a academia.',select:null}
 ];
 return <div className="role-screen screen"><div className="topbar"><Brand/>{onBack&&<button className="text-link" onClick={onBack}>Voltar</button>}</div><Heading eyebrow="Ambiente de demonstração" title="Entre para testar" description="Escolha um perfil. Todos compartilham os exemplos deste navegador."/><div className="role-options">{options.map(o=><article className="role-card" key={o.role}><button className="role-card-main" onClick={()=>onChoose({role:o.role,id:o.id})}><span className="role-icon"><o.icon/></span><span><strong>{o.title}</strong><small>{o.description}</small></span><ArrowUpRight/></button>{o.select&&<div className="role-person">{o.select}<button className="role-enter" aria-label={`Entrar como ${o.title}`} onClick={()=>onChoose({role:o.role,id:o.id})}><ArrowRight/></button></div>}</article>)}</div><div className="dev-explanation"><Shield size={18}/><p>Seletor temporário de desenvolvimento. Será removido quando a autenticação real entrar. Aqui não há login, banco de dados ou biometria.</p></div></div>;
}
export function PeopleList({data,students,onSelect,heading='Alunos'}:{data:DemoData;students:Student[];onSelect:(id:string)=>void;heading?:string}){
 const [search,setSearch]=useState('');const rows=students.filter(s=>normalize(s.name).includes(normalize(search)));
 return <div className="screen"><Heading eyebrow={data.actor?.role==='teacher'?'Seu acompanhamento':'Visão da academia'} title={heading} description={`${students.length} alunos neste ambiente de exemplo`}/><label className="search-box"><Search/><input aria-label="Buscar aluno" placeholder="Buscar pelo nome" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="students-list">{rows.map(s=><StudentRow key={s.id} student={s} teacherName={data.teachers.find(t=>t.id===s.teacherId)?.name} planCount={studentPlans(data,s.id).length} onClick={()=>onSelect(s.id)}/>)}</div>{!rows.length&&<Empty title={students.length?'Nenhum aluno encontrado':'Nenhum aluno vinculado'} description={students.length?'Tente outro nome.':'Este professor ainda não possui alunos demonstrativos vinculados.'}/>}</div>;
}
export function TeacherHome({data,onSelect,onStudents}:{data:DemoData;onSelect:(id:string)=>void;onStudents:()=>void}){
 const teacher=data.teachers.find(t=>t.id===data.actor?.id)!;const students=data.students.filter(s=>s.teacherId===teacher.id);const plans=data.plans.filter(p=>students.some(s=>s.id===p.studentId));const pending=students.filter(s=>!studentPlans(data,s.id).length);
 return <div className="screen"><Heading eyebrow="Seu espaço de acompanhamento" title={`Olá, ${teacher.name.split(' ')[0]}`} description="Um plano bem feito começa por conhecer o aluno."/><div className="quick-stats"><div className="quick-stat"><Users/><div className="stat-value">{students.length}</div><span className="stat-label">Seus alunos</span></div><div className="quick-stat"><BookOpen/><div className="stat-value">{plans.filter(p=>p.published).length}</div><span className="stat-label">Publicadas</span></div><div className="quick-stat"><Dumbbell/><div className="stat-value">{plans.filter(hasChanges).length}</div><span className="stat-label">Rascunhos</span></div></div><button className="primary-btn" onClick={onStudents}>Montar ficha para um aluno<ArrowRight/></button>{pending.length>0&&<section className="section-space"><Section title="Aguardando primeira ficha"/><div className="students-list">{pending.map(s=><StudentRow key={s.id} student={s} planCount={0} onClick={()=>onSelect(s.id)}/>)}</div></section>}<section className="section-space"><Section title="Seus alunos" action={students.length?<button className="text-link" onClick={onStudents}>Ver todos<ArrowUpRight/></button>:undefined}/>{students.length?<div className="students-list">{students.map(s=><StudentRow key={s.id} student={s} planCount={studentPlans(data,s.id).length} onClick={()=>onSelect(s.id)}/>)}</div>:<Empty title="Nenhum aluno vinculado" description="Este perfil permite validar o estado vazio do professor sem alterar os outros exemplos."/>}</section><div className="flow-note"><GraduationCap/><p>Salve uma ficha como rascunho para continuar depois. Ao publicar, ela aparece no perfil do aluno escolhido.</p></div></div>;
}
export function AdminHome({data,onStudents,onTeachers}:{data:DemoData;onStudents:()=>void;onTeachers:()=>void}){
 const active=data.students.filter(s=>statistics(studentHistory(data,s.id)).current.length>0).length;
 return <div className="screen"><Heading eyebrow={data.gym.name} title="Visão da academia" description="Alunos, acompanhamento e atividade em um só lugar."/><div className="admin-overview"><div><Users/><strong>{data.students.length}</strong><span>Alunos</span></div><div><GraduationCap/><strong>{data.teachers.length}</strong><span>Professores</span></div><div><Dumbbell/><strong>{data.plans.filter(p=>p.published).length}</strong><span>Fichas publicadas</span></div><div><User/><strong>{active}</strong><span>Ativos na semana</span></div></div><Section title="Acompanhar"/><button className="next-row" onClick={onStudents}><span className="role-icon"><Users/></span><div><strong>Alunos da academia</strong><p>{data.students.filter(s=>s.mode==='accompanied').length} acompanhados · {data.students.filter(s=>s.mode==='autonomous').length} autônomos</p></div><ChevronRight/></button><button className="next-row section-gap" onClick={onTeachers}><span className="role-icon"><GraduationCap/></span><div><strong>Equipe de professores</strong><p>Alunos vinculados e especialidades</p></div><ChevronRight/></button><section className="section-space"><Section title="Atividade recente"/><div className="history-list">{data.history.slice(0,5).map(r=><div className="history-row" key={r.id}><span className="history-icon"><Dumbbell/></span><div><strong>{data.students.find(s=>s.id===r.studentId)?.name}</strong><p>Ficha {r.letter} · {r.name}</p></div><span>{new Date(r.date).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</span></div>)}{!data.history.length&&<p className="empty-history">Nenhum treino concluído foi registrado neste ambiente.</p>}</div></section><p className="help-text">Visão administrativa demonstrativa, sem dados financeiros ou cadastros reais.</p></div>;
}
export function TeacherList({data,onSelect}:{data:DemoData;onSelect:(id:string)=>void}){return <div className="screen"><Heading eyebrow="Pessoas que acompanham" title="Professores" description="Equipe demonstrativa da academia."/>{data.teachers.map(t=><div className="teacher-card" key={t.id}><div className="teacher-header"><Avatar name={t.name}/><div><h2>{t.name}</h2><p>{t.specialty}</p></div></div><span className="chip">{data.students.filter(s=>s.teacherId===t.id).length} alunos vinculados</span><div className="teacher-students">{data.students.filter(s=>s.teacherId===t.id).map(s=><button key={s.id} onClick={()=>onSelect(s.id)}>{s.name}<ChevronRight size={15}/></button>)}{!data.students.some(s=>s.teacherId===t.id)&&<p className="teacher-empty">Nenhum aluno vinculado neste exemplo.</p>}</div></div>)}</div>;}
export function GymInfo({data}:{data:DemoData}){return <div className="screen"><Heading eyebrow="Informações institucionais" title="Academia"/><div className="gym-brand"><Brand/><h2>{data.gym.name}</h2><p>{data.gym.city}</p><span className="chip">Unidade de demonstração</span></div><div className="gym-details">{[['Localização',data.gym.address],['Horário',data.gym.hours],['Contato',data.gym.email],['Em atividade desde',data.gym.since],['Equipe',`${data.teachers.length} professores · ${data.students.length} alunos`]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="help-text">Todas as informações desta unidade são exemplos para testar a estrutura interna do aplicativo.</p></div>;}
