"use client";
import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowRight, ArrowUpRight, BookOpen, Building2, Check, CheckCheck, ChevronRight, Clock3, Dumbbell, Edit3, GraduationCap, Home, Info, Minus, Plus, Repeat2, RotateCcw, Target, Trash2, User, Users } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { Avatar, Back, Brand, Empty, ExerciseArt, Heading, PlanCard, Section } from './ui';
import { ExerciseDetails, ExerciseLibrary } from './library';
import { PlanEditor } from './editor';
import { Evolution } from './progress';
import { ActiveTraining } from './session';
import { AdminHome, GymInfo, PeopleList, RoleSelector, TeacherHome, TeacherList } from './people';
import { StudentHome } from './home';
import { canManageStudent, changeSet, clone, completedSets, createDemo, discardSession, duration, exerciseById, finishSession, hasChanges, newId, planMinutes, recordSets, recordVolume, removePlan, restoreSavedData, ROLE_LABELS, savePlan, startSession, statistics, STORAGE_KEY, LEGACY_STORAGE_KEY, studentHistory, studentPlans, switchActor, togglePause, updateSession } from './model';
import type { Actor, DemoData, Exercise, PlanContent, Role, Screen, TrainingPlan, TrainingRecord } from './types';

type EditorState={id:string;studentId:string;content:PlanContent;original:PlanContent;isNew:boolean;back:Screen};
type Confirm={type:'finish'|'discard'|'delete'|'reset'|'leave';next?:Screen|'roles'};
const studentNav=[{screen:'home',label:'Início',icon:Home},{screen:'plans',label:'Treinos',icon:Dumbbell},{screen:'library',label:'Biblioteca',icon:BookOpen},{screen:'progress',label:'Evolução',icon:Activity}] as const;
const teacherNav=[{screen:'home',label:'Início',icon:Home},{screen:'students',label:'Alunos',icon:Users},{screen:'library',label:'Biblioteca',icon:BookOpen},{screen:'profile',label:'Perfil',icon:User}] as const;
const adminNav=[{screen:'home',label:'Início',icon:Home},{screen:'students',label:'Alunos',icon:Users},{screen:'teachers',label:'Equipe',icon:GraduationCap},{screen:'gym',label:'Academia',icon:Building2}] as const;
export default function PerformanceApp(){
 const [data,setData]=useState<DemoData|null>(null);const dataRef=useRef<DemoData|null>(null);
 const [screen,setScreen]=useState<Screen>('home');const [showRoles,setShowRoles]=useState(false);
 const [studentId,setStudentId]=useState('caue');const [planId,setPlanId]=useState<string|null>(null);const [detailBack,setDetailBack]=useState<Screen>('plans');
 const [editor,setEditor]=useState<EditorState|null>(null);const [confirm,setConfirm]=useState<Confirm|null>(null);
 const [result,setResult]=useState<TrainingRecord|null>(null);const [exercise,setExercise]=useState<Exercise|null>(null);
 const [modal,setModal]=useState<'goal'|'about'|null>(null);const [goalDraft,setGoalDraft]=useState(4);
 const [date,setDate]=useState<Date|null>(null);const saveError=useRef(false);
 useEffect(()=>{const now=new Date();setDate(now);let restored:DemoData|null=null;try{const raw=localStorage.getItem(STORAGE_KEY)??localStorage.getItem(LEGACY_STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);restored=restoreSavedData(parsed);if(!restored)toast('Os exemplos foram restaurados porque os dados locais estavam incompletos.');}}catch{toast('Os exemplos estão disponíveis nesta sessão.');}const next=restored??createDemo(now);dataRef.current=next;setData(next);},[]);
 useEffect(()=>{if(!data)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.removeItem(LEGACY_STORAGE_KEY);}catch{if(!saveError.current){toast.error('Não foi possível salvar neste navegador. As alterações ficam disponíveis até fechar a página.');saveError.current=true;}}},[data]);
 useEffect(()=>{if(!editor||JSON.stringify(editor.content)===JSON.stringify(editor.original))return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[editor]);
 function commit(action:(current:DemoData)=>DemoData):boolean{try{const current=dataRef.current;if(!current)return false;const next=action(current);dataRef.current=next;setData(next);setDate(new Date());try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));localStorage.removeItem(LEGACY_STORAGE_KEY);}catch{if(!saveError.current){toast.error('Não foi possível salvar neste navegador. As alterações ficam disponíveis até fechar a página.');saveError.current=true;}}return true;}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível concluir a ação.');return false;}}
 function go(next:Screen,force=false){if(!force&&editor&&JSON.stringify(editor.content)!==JSON.stringify(editor.original)){setConfirm({type:'leave',next});return;}if(screen==='editor'&&next!=='editor')setEditor(null);setScreen(next);window.scrollTo({top:0,behavior:'instant'});}
 function roles(){if(editor&&JSON.stringify(editor.content)!==JSON.stringify(editor.original)){setConfirm({type:'leave',next:'roles'});return;}setShowRoles(true);window.scrollTo({top:0,behavior:'instant'});}
 function chooseRole(actor:Actor){if(commit(d=>switchActor(d,actor))){setShowRoles(false);setEditor(null);setPlanId(null);setConfirm(null);setModal(null);setExercise(null);go('home',true);toast(`${ROLE_LABELS[actor.role]} · demonstração`);}}
 function openStudent(id:string){setStudentId(id);go('student');}
 function openPlan(id:string){setPlanId(id);setDetailBack(screen);go('detail');}
 function beginEdit(student:string,plan?:TrainingPlan){const current=dataRef.current;if(!current||!canManageStudent(current,student)){toast.error('Este perfil apenas recebe e executa as fichas.');return;}const letter=['A','B','C','D','E','F'].find(l=>!current.plans.some(p=>p.studentId===student&&p.draft.letter===l));if(!plan&&!letter){toast('Você já tem fichas de A a F. Edite uma ficha existente.');return;}const content=plan?clone(plan.draft):{letter:letter!,name:'',notes:'',exercises:[]};setEditor({id:plan?.id??newId(),studentId:student,content,original:clone(content),isNew:!plan,back:current.actor?.role==='teacher'?'student':'plans'});setStudentId(student);go('editor',true);}
 function persistEditor(publish:boolean){if(!editor)return;if(commit(d=>savePlan(d,editor.studentId,editor.id,editor.content,publish))){toast.success(publish?'Ficha publicada e disponível para o aluno.':'Rascunho salvo. A ficha do aluno continua igual.');const back=editor.back;setEditor(null);go(back,true);}}
 function beginSession(id:string){const current=dataRef.current;if(!current?.actor)return;const running=current.sessions[current.actor.id];if(running){if(running.planId!==id)toast('Você tem outro treino em andamento. Continue ou descarte antes de trocar.');go('session');return;}if(commit(d=>startSession(d,id)))go('session');}
 function finish(){let record:TrainingRecord|null=null;if(commit(d=>{const finished=finishSession(d);record=finished.record;return finished.data;})){setResult(record);setConfirm(null);go('success',true);}}
 function acceptConfirm(){if(!confirm)return;switch(confirm.type){case 'finish':finish();break;case 'discard':if(commit(discardSession)){setConfirm(null);go('home',true);toast('Treino descartado.');}break;case 'delete':if(planId&&commit(d=>removePlan(d,planId))){setConfirm(null);go(dataRef.current?.actor?.role==='teacher'?'student':'plans',true);toast('Ficha removida. O histórico foi mantido.');}break;case 'reset':commit(d=>{const next=createDemo();return {...next,actor:d.actor};});setEditor(null);setResult(null);setConfirm(null);go('home',true);toast.success('Exemplos restaurados.');break;case 'leave':{const next=confirm.next;setEditor(null);setConfirm(null);if(next==='roles'){setShowRoles(true);setScreen('home');}else if(next)go(next,true);break;}}}
 // These optional page tools share the exact visible demo state. No external service is required.
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_performance_demo',description:'Lê o perfil ativo e as fichas disponíveis no ambiente demonstrativo Performance.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>{const d=dataRef.current;return d?{actor:d.actor,students:d.students.map(s=>({id:s.id,name:s.name,mode:s.mode})),plans:d.plans.filter(p=>d.actor?.role==='admin'||d.actor?.role==='teacher'&&d.students.some(s=>s.id===p.studentId&&s.teacherId===d.actor?.id)||p.studentId===d.actor?.id&&p.published).map(p=>({id:p.id,studentId:p.studentId,name:p.published?.name??p.draft.name,published:!!p.published}))}:{ready:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 if(!data||!date)return <div className="app-shell"><main className="app-main"><Brand/><p className="loading-demo" role="status">Preparando a demonstração…</p></main></div>;
 const actor=data.actor;
 if(!actor||showRoles)return <div className="app-shell"><main className="app-main selector-main"><RoleSelector data={data} onChoose={chooseRole} onBack={actor?()=>setShowRoles(false):undefined}/></main><Toaster theme="dark" position="top-center"/></div>;
 const isStudent=actor.role==='autonomous'||actor.role==='accompanied';const self=data.students.find(s=>s.id===actor.id);
 const personName=isStudent?self!.name:actor.role==='teacher'?data.teachers.find(t=>t.id===actor.id)!.name:'Admin';
 const plans=isStudent?studentPlans(data,actor.id):[];const history=isStudent?studentHistory(data,actor.id):[];const session=data.sessions[actor.id];
 const selectedStudent=data.students.find(s=>s.id===studentId);const managedStudents=actor.role==='teacher'?data.students.filter(s=>s.teacherId===actor.id):data.students;
 const selectedPlan=data.plans.find(p=>p.id===planId);const editable=selectedPlan?canManageStudent(data,selectedPlan.studentId):false;
 const detailContent=selectedPlan?(editable||actor.role==='admin'?selectedPlan.draft:selectedPlan.published):null;
 const nav=actor.role==='admin'?adminNav:actor.role==='teacher'?teacherNav:studentNav;
 const standardScreen=['home','plans','library','progress','profile','students','teachers','gym'].includes(screen);
 const confirmationTitle=confirm?.type==='finish'?'Finalizar por hoje?':confirm?.type==='discard'?'Descartar este treino?':confirm?.type==='delete'?'Excluir esta ficha?':confirm?.type==='reset'?'Restaurar os exemplos?':'Sair sem salvar?';
 const confirmationText=confirm?.type==='finish'?'Há séries em aberto. Apenas as séries marcadas serão registradas.':confirm?.type==='discard'?'O treino em andamento será descartado. Seu histórico anterior será mantido.':confirm?.type==='delete'?'A ficha deixará de aparecer para o aluno. Treinos já registrados serão preservados.':confirm?.type==='reset'?'As fichas, treinos e metas deste navegador serão substituídos pelos dados demonstrativos iniciais.':'Suas alterações ainda não foram salvas. Você pode continuar editando ou descartá-las.';
 return <div className="app-shell"><main className="app-main">
  {standardScreen&&<header className="topbar"><Brand/><button className="profile-button" aria-label="Abrir perfil" onClick={()=>go('profile')}><Avatar name={personName}/></button></header>}
  {screen!=='session'&&screen!=='editor'&&screen!=='success'&&<button className="development-bar" onClick={roles}><span><span className="dev-label">DEMO</span>{ROLE_LABELS[actor.role]}</span><span>Trocar<Repeat2 size={14}/></span></button>}
  {screen==='home'&&isStudent&&<StudentHome student={self!} teacherName={data.teachers.find(t=>t.id===self?.teacherId)?.name} plans={plans} history={history} session={session} now={date} onStart={beginSession} onPlans={()=>go('plans')} onProgress={()=>go('progress')} onNew={()=>beginEdit(actor.id)} onDetail={openPlan}/>}
  {screen==='home'&&actor.role==='teacher'&&<TeacherHome data={data} onSelect={openStudent} onStudents={()=>go('students')}/>}
  {screen==='home'&&actor.role==='admin'&&<AdminHome data={data} onStudents={()=>go('students')} onTeachers={()=>go('teachers')}/>}
  {screen==='plans'&&isStudent&&<div className="screen"><Heading eyebrow={actor.role==='autonomous'?'Sua rotina, do seu jeito':'Acompanhamento profissional'} title="Seus treinos" description={actor.role==='autonomous'?'Monte, ajuste e execute suas fichas.':'Fichas publicadas pelo seu professor.'} action={actor.role==='autonomous'&&<button className="icon-button neon-icon" aria-label="Criar nova ficha" onClick={()=>beginEdit(actor.id)}><Plus/></button>}/>{plans.map(p=><PlanCard key={p.id} plan={p} content={p.published!} editable={actor.role==='autonomous'} onClick={()=>openPlan(p.id)}/>)}{!plans.length&&<Empty title="Nenhuma ficha disponível" description={actor.role==='autonomous'?'Crie sua primeira ficha com os exercícios da biblioteca.':'Aguarde a publicação da ficha pelo professor.'}/>}<p className="help-text">{actor.role==='autonomous'?'As fichas deste perfil são criadas e editadas por você.':'Você pode consultar e executar as fichas. A criação e a publicação ficam com o professor.'}</p></div>}
  {screen==='library'&&<ExerciseLibrary/>}
  {screen==='progress'&&isStudent&&<Evolution key={actor.id} student={self!} history={history} now={date}/>}
  {screen==='students'&&!isStudent&&<PeopleList data={data} students={managedStudents} onSelect={openStudent}/>}
  {screen==='teachers'&&actor.role==='admin'&&<TeacherList data={data} onSelect={openStudent}/>}
  {screen==='gym'&&actor.role==='admin'&&<GymInfo data={data}/>}
  {screen==='student'&&selectedStudent&&!isStudent&&managedStudents.some(s=>s.id===selectedStudent.id)&&<div className="screen"><Back onClick={()=>go('students')} label="Perfil do aluno"/><div className="student-profile-head"><Avatar name={selectedStudent.name} large/><h1>{selectedStudent.name}</h1><span className="chip">{selectedStudent.mode==='autonomous'?'Autônomo':'Acompanhado'}</span><p>{selectedStudent.objective}</p><p className="small muted">{data.teachers.find(t=>t.id===selectedStudent.teacherId)?.name??'Treina por conta própria'}</p></div><div className="student-summary"><span><strong>{studentHistory(data,studentId).length}</strong>treinos</span><span><strong>{statistics(studentHistory(data,studentId),date).streak}</strong>semanas seguidas</span><span><strong>{selectedStudent.goal}</strong>meta semanal</span></div><Section title="Fichas de treino" action={canManageStudent(data,studentId)&&<button className="text-link" onClick={()=>beginEdit(studentId)}><Plus/>Nova ficha</button>}/>{studentPlans(data,studentId,true).map(p=><PlanCard key={p.id} plan={p} content={p.draft} editable onClick={()=>openPlan(p.id)}/>)}{!studentPlans(data,studentId,true).length&&<Empty title="Ainda sem ficha" description="As fichas aparecerão aqui quando forem montadas."/>}<Section title="Histórico de treinos"/><div className="history-list">{studentHistory(data,studentId).slice(0,8).map(h=><div className="history-row" key={h.id}><span className="history-icon"><Check/></span><div><strong>{h.letter} · {h.name}</strong><p>{recordSets(h)} séries · {h.sample?'Exemplo':'Registrado neste teste'}</p></div><span>{new Date(h.date).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</span></div>)}{!studentHistory(data,studentId).length&&<p className="empty-history">Este aluno ainda não tem treinos registrados.</p>}</div></div>}
  {screen==='detail'&&selectedPlan&&detailContent&&<div className="screen"><Back onClick={()=>go(detailBack)} label={`Ficha ${detailContent.letter}`} children={editable?<button className="icon-button" aria-label="Editar ficha" onClick={()=>beginEdit(selectedPlan.studentId,selectedPlan)}><Edit3/></button>:undefined}/><div className="detail-heading"><span className="workout-label">TREINO {detailContent.letter} · {editable&&hasChanges(selectedPlan)?'RASCUNHO':`VERSÃO ${selectedPlan.revision}`}</span><h1>{detailContent.name}<span className="green">.</span></h1><div className="feature-meta"><span><Clock3/>~{planMinutes(detailContent)} min</span><span><Dumbbell/>{detailContent.exercises.length} exercícios</span></div></div>{detailContent.notes&&<div className="plan-notes"><Info size={17}/><p>{detailContent.notes}</p></div>}<div className="exercise-list illustrated-list">{detailContent.exercises.map((line,i)=>{const ex=exerciseById(line.exerciseId)!;return <button className="illustrated-exercise" key={line.id} onClick={()=>setExercise(ex)}><div className="exercise-thumb"><ExerciseArt exercise={ex}/></div><div><span className="muscle-label">{String(i+1).padStart(2,'0')} · {ex.group}</span><h3>{ex.name}</h3><p>{line.sets} × {line.reps}{ex.unit==='seconds'?'s':' reps'} · {line.kg} kg</p><p>{line.rest}s de descanso</p></div><ChevronRight size={16}/></button>;})}</div>{editable&&<button className="text-link danger" onClick={()=>setConfirm({type:'delete'})}><Trash2/>Excluir ficha</button>}{isStudent?<div className="sticky-action"><button className="primary-btn" onClick={()=>beginSession(selectedPlan.id)}><Dumbbell/>{session?'Continuar treino em andamento':'Iniciar este treino'}<ArrowRight/></button></div>:editable?<div className="sticky-action"><button className="primary-btn" onClick={()=>beginEdit(selectedPlan.studentId,selectedPlan)}><Edit3/>Editar e publicar ficha</button></div>:<p className="help-text">Visualização administrativa. A ficha é gerenciada pelo professor ou pelo aluno autônomo.</p>}</div>}
  {screen==='editor'&&editor&&<PlanEditor key={editor.id} content={editor.content} student={data.students.find(s=>s.id===editor.studentId)!} isTeacher={actor.role==='teacher'} isNew={editor.isNew} onChange={content=>setEditor(e=>e?{...e,content}:e)} onBack={()=>go(editor.back)} onSave={persistEditor}/>}
  {screen==='session'&&session&&isStudent&&<ActiveTraining session={session} onBack={()=>go('home')} onPause={()=>commit(togglePause)} onSet={(i,j,patch)=>commit(d=>changeSet(d,i,j,patch))} onIndex={index=>commit(d=>updateSession(d,s=>({...s,exerciseIndex:Math.max(0,Math.min(s.snapshot.exercises.length-1,index))})))} onRest={seconds=>commit(d=>updateSession(d,s=>({...s,restEndsAt:seconds?Date.now()+seconds*1000:null,restPausedSeconds:null})))} onFinish={()=>completedSets(session)<session.sets.flat().length?setConfirm({type:'finish'}):finish()} onDiscard={()=>setConfirm({type:'discard'})}/>}
  {screen==='success'&&result&&<div className="screen success-screen"><div className="success-mark"><CheckCheck/></div><div><span className="eyebrow green">Mais um passo à frente</span><h1>Treino<br/>concluído<span className="green">.</span></h1></div><p>Boa, {personName.split(' ')[0]}! Seu treino entrou no histórico.</p><div className="quick-stats"><div className="quick-stat"><div className="stat-value time-value">{duration(result.seconds)}</div><span className="stat-label">Tempo total</span></div><div className="quick-stat"><div className="stat-value">{recordSets(result)}</div><span className="stat-label">Séries feitas</span></div><div className="quick-stat"><div className="stat-value">{(recordVolume(result)/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})}<small>t</small></div><span className="stat-label">Volume</span></div></div><button className="primary-btn" onClick={()=>go('progress')}>Ver minha evolução<ArrowRight/></button><button className="text-link muted" onClick={()=>go('home')}>Voltar ao início</button></div>}
  {screen==='profile'&&<div className="screen"><Heading eyebrow="Do seu jeito" title="Meu perfil"/><div className="profile-card"><Avatar name={personName} large/><h2>{personName}</h2><span className="chip">{ROLE_LABELS[actor.role]}</span><p className="profile-demo-caption">Perfil de demonstração</p></div><div className="settings-group">{isStudent&&<button className="settings-row" onClick={()=>{setGoalDraft(self!.goal);setModal('goal');}}><Target/>Meta semanal<span>{self!.goal} treinos</span><ChevronRight/></button>}<button className="settings-row" onClick={roles}><Repeat2/>Trocar perfil de teste<ChevronRight/></button><button className="settings-row" onClick={()=>setModal('about')}><Info/>Sobre esta versão<ChevronRight/></button><button className="settings-row danger" onClick={()=>setConfirm({type:'reset'})}><RotateCcw/>Restaurar exemplos<ChevronRight/></button></div><div className="profile-foot"><Brand/><p>Versão 2.0 · Ambiente de desenvolvimento</p></div></div>}
 </main>
 {standardScreen&&<nav className="bottom-nav" aria-label="Navegação principal"><div className="nav-inner">{nav.map(item=><button key={item.screen} className={`nav-item ${screen===item.screen?'active':''}`} aria-current={screen===item.screen?'page':undefined} onClick={()=>go(item.screen)}><item.icon/><span>{item.label}</span></button>)}</div></nav>}
 <ExerciseDetails exercise={exercise} onClose={()=>setExercise(null)}/>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null);}}><DialogContent className="app-modal">{modal==='goal'?<><DialogTitle>Sua meta, seu ritmo</DialogTitle><DialogDescription>Quantos treinos você quer fazer por semana?</DialogDescription><div className="goal-controls"><button aria-label="Diminuir meta" disabled={goalDraft<=1} onClick={()=>setGoalDraft(g=>g-1)}><Minus/></button><strong>{goalDraft}</strong><button aria-label="Aumentar meta" disabled={goalDraft>=7} onClick={()=>setGoalDraft(g=>g+1)}><Plus/></button></div><button className="primary-btn" onClick={()=>{commit(d=>({...d,students:d.students.map(s=>s.id===actor.id?{...s,goal:goalDraft}:s)}));setModal(null);toast.success('Meta atualizada.');}}>Salvar meta<Check size={18}/></button></>:<><DialogTitle>Performance · demonstração</DialogTitle><DialogDescription>Teste o ciclo completo sem cadastrar uma conta real.</DialogDescription><p className="small muted">Troque entre aluno autônomo, aluno acompanhado, professor e admin. Fichas publicadas e treinos registrados ficam compartilhados entre os perfis deste navegador.</p><p className="small muted">Os dados são exemplos locais. O seletor de desenvolvimento será removido quando a autenticação real for implementada. Não há Firebase, banco real ou biometria nesta fase.</p><button className="primary-btn" onClick={()=>setModal(null)}>Continuar explorando<ArrowRight/></button></>}</DialogContent></Dialog>
 <AlertDialog open={confirm!==null} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent className="app-modal"><AlertDialogTitle>{confirmationTitle}</AlertDialogTitle><AlertDialogDescription>{confirmationText}</AlertDialogDescription><div className="dialog-actions"><AlertDialogAction className="primary-btn" onClick={acceptConfirm}>{confirm?.type==='finish'?'Salvar e finalizar':confirm?.type==='leave'?'Sair sem salvar':confirm?.type==='reset'?'Restaurar exemplos':confirm?.type==='delete'?'Excluir ficha':'Descartar treino'}</AlertDialogAction><AlertDialogCancel className="secondary-btn">{confirm?.type==='leave'?'Continuar editando':'Cancelar'}</AlertDialogCancel></div></AlertDialogContent></AlertDialog>
 <Toaster theme="dark" position="top-center" visibleToasts={2} toastOptions={{style:{background:'#272727',color:'#f5f5f5',border:'none',borderRadius:14,width:'min(360px,calc(100vw - 32px))'}}}/>
 </div>;
}
