"use client";
import { useEffect, useState } from 'react';
import { ArrowRight, CheckCheck, ChevronLeft, ChevronRight, Clock3, Pause, Play, X } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { Back, ExerciseArt } from './ui';
import { clock, completedSets, elapsed, exerciseById } from './model';
import type { TrainingSession } from './types';
export function ActiveTraining({session,onBack,onPause,onSet,onIndex,onRest,onFinish,onDiscard}:{session:TrainingSession;onBack:()=>void;onPause:()=>void;onSet:(i:number,j:number,patch:Partial<{kg:number;reps:number;done:boolean}>)=>void;onIndex:(index:number)=>void;onRest:(seconds:number)=>void;onFinish:()=>void;onDiscard:()=>void}){
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),500);return()=>window.clearInterval(timer);},[]);
 const i=session.exerciseIndex,line=session.snapshot.exercises[i],exercise=exerciseById(line.exerciseId)!;
 const done=completedSets(session),total=session.sets.flat().length,paused=session.pausedAt!==null;
 const rest=session.restPausedSeconds??(session.restEndsAt?Math.max(0,Math.ceil((session.restEndsAt-now)/1000)):0);
 return <div className="screen"><Back onClick={onBack} label={`Treino ${session.snapshot.letter}`}><div className="session-timer"><Clock3/>{clock(elapsed(session,now))}</div><button className="icon-button" aria-label={paused?'Retomar treino':'Pausar treino'} onClick={onPause}>{paused?<Play/>:<Pause/>}</button></Back><div className="session-progress"><div className="section-heading"><span>{session.snapshot.name}</span><span>{done}/{total} séries</span></div><Progress className="app-progress" value={done/total*100} aria-label="Séries concluídas"/></div>{paused&&<div className="pause-banner">Treino pausado. Toque em play para continuar.</div>}<div className="session-card"><span className="eyebrow">Exercício {String(i+1).padStart(2,'0')} / {String(session.snapshot.exercises.length).padStart(2,'0')}</span><h1>{exercise.name}</h1><div className="session-art"><ExerciseArt exercise={exercise}/></div><p className="exercise-note">{exercise.group} · {line.rest}s de descanso</p><div className="sets-head"><span>Série</span><span>Carga / kg</span><span>{exercise.unit==='seconds'?'Tempo / s':'Reps'}</span><span>Feito</span></div>{session.sets[i].map((entry,j)=><div className={`set-row ${entry.done?'complete':''}`} key={`${i}-${j}`}><span>{String(j+1).padStart(2,'0')}</span><input className="set-input" type="number" min={0} max={1000} step={.5} inputMode="decimal" aria-label={`Carga da série ${j+1} em kg`} value={entry.kg} disabled={paused} onChange={e=>onSet(i,j,{kg:e.target.value===''?0:Number(e.target.value)})}/><input className="set-input" type="number" min={1} max={300} inputMode="numeric" aria-label={`${exercise.unit==='seconds'?'Segundos':'Repetições'} da série ${j+1}`} value={entry.reps} disabled={paused} onChange={e=>{const value=Number(e.target.value);if(value>=1)onSet(i,j,{reps:value});}}/><Checkbox className="set-check" aria-label={`Concluir série ${j+1}`} checked={entry.done} disabled={paused} onCheckedChange={v=>onSet(i,j,{done:v===true})}/></div>)}<p className="set-hint">Registre o realizado. A ficha original permanece igual.</p></div><div className="rest-box"><div><p>{rest>0?'Descanso em andamento':'Descanso'}</p><strong>{clock(rest)}</strong></div><div className="rest-controls"><button disabled={paused} onClick={()=>onRest(rest+30)}>+30s</button><button disabled={paused||rest===0} aria-label="Pular descanso" onClick={()=>onRest(0)}><ChevronRight/></button></div></div><div className="exercise-pagination"><button disabled={i===0} onClick={()=>onIndex(i-1)}><ChevronLeft/>Anterior</button><span>{i+1} de {session.snapshot.exercises.length}</span><button disabled={i===session.snapshot.exercises.length-1} onClick={()=>onIndex(i+1)}>Próximo<ChevronRight/></button></div><button className="text-link muted" onClick={onDiscard}><X/>Descartar treino</button><div className="sticky-action"><button className="primary-btn" disabled={done===0} onClick={onFinish}><CheckCheck/>Finalizar treino<ArrowRight className="push-icon"/></button></div></div>;
}
