"use client";
import type { ReactNode } from 'react';
import { ArrowLeft, ArrowUpRight, BookOpen, ChevronRight, Dumbbell, Zap } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { Exercise, PlanContent, Student, TrainingPlan } from './types';
import { hasChanges, planMinutes } from './model';
export function Brand(){return <div className="brand"><Zap fill="currentColor" aria-hidden="true"/><span>performance</span></div>;}
export function Back({onClick,label,children}:{onClick:()=>void;label:string;children?:ReactNode}){return <div className="back-header"><button type="button" className="icon-button" aria-label="Voltar" onClick={onClick}><ArrowLeft/></button><span>{label}</span>{children??<span style={{width:44}}/>}</div>;}
export function Heading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="page-header">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<div className="page-heading-row"><h1>{title}<span className="green">.</span></h1>{action}</div>{description&&<p>{description}</p>}</header>;}
export function Section({title,action}:{title:string;action?:ReactNode}){return <div className="section-heading"><h2>{title}</h2>{action}</div>;}
export function Choose({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="app-select" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper" className="app-select-list">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty-card"><span className="empty-icon"><Dumbbell/></span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Avatar({name,large=false}:{name:string;large?:boolean}){return <span className={large?'profile-avatar':'avatar'}>{name.split(/\s+/).filter(Boolean).map(s=>s[0]).slice(0,2).join('').toUpperCase()}</span>;}
export function ExerciseArt({exercise,large=false}:{exercise:Exercise;large?:boolean}){return <div className={`exercise-art ${large?'large':''}`}><img className="movement-image" src={exercise.images[0]} alt={`Ilustração de ${exercise.name}`} loading="lazy"/><div className="muscle-figure"><img src={exercise.muscleImage} alt={`${exercise.group} destacado em verde`} loading="lazy"/>{large&&<span>Foco muscular</span>}</div></div>;}
export function PlanCard({plan,content,onClick,editable=false}:{plan:TrainingPlan;content:PlanContent;onClick:()=>void;editable?:boolean}){return <button className="plan-card compact-plan" onClick={onClick}><div className="plan-top"><span className="plan-letter">{content.letter}</span><span className={`chip ${plan.published?'published':''}`}>{editable&&hasChanges(plan)?plan.published?'Alterações em rascunho':'Rascunho':`Publicada · v${plan.revision}`}</span></div><h2>{content.name}</h2><div className="plan-bottom"><div className="feature-meta"><span><Dumbbell/>{content.exercises.length} exercícios</span><span>{planMinutes(content)} min estimados</span></div><ArrowUpRight/></div></button>;}
export function StudentRow({student,teacherName,planCount,onClick}:{student:Student;teacherName?:string;planCount:number;onClick:()=>void}){return <button className="student-row" onClick={onClick}><Avatar name={student.name}/><div><strong>{student.name}</strong><span>{student.mode==='autonomous'?'Autônomo':teacherName??'Acompanhado'} · {planCount} {planCount===1?'ficha':'fichas'}</span></div><ChevronRight/></button>;}
export function Credits(){return <div className="image-credits"><BookOpen size={15}/><p>Ilustrações: <a href="https://github.com/bryllim/workout-guide" target="_blank" rel="noreferrer">Workout Guide / Bryl Lim</a> e <a href="https://github.com/everkinetic/data" target="_blank" rel="noreferrer">Everkinetic / Greg Priday</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>. Anatomia: <a href="https://github.com/HichamELBSI/react-native-body-highlighter" target="_blank" rel="noreferrer">Body Highlighter</a> · MIT. Cores dos mapas adaptadas para o Performance. <a href="/exercise-credits.json" target="_blank" rel="noreferrer">Créditos por exercício</a>.</p></div>;}
